### ISSUE TITLE
Location coming out as null

### ISSUE THREAD

**Issue by arp95** [LakshayNagpal/MapsMarker#7]
For one day i am trying to show users location but it always return null no matter what changes i make.
I went through many stackoverflow issues but they didnt give a useful result.

@LakshayNagpal 
any ideas?

**Comment by LakshayNagpal** [comment]
@arp95 

I have seen many repo's with the same concept, it's just that they are either restaurant or coffee or anything else but not beer and wine

So should I provide you with some similar repos and then you can understand their code and make required changes in it?

**Comment by arp95** [comment]
@LakshayNagpal
yes share it. Actually i will share my code by tonight and have tried everything i could. Lets see what those repos offer.

**Comment by LakshayNagpal** [comment]
https://github.com/slidenerd/CofShop

https://github.com/dinesh-vdl/PubFinder

https://github.com/marcbaldwin/Nearby

https://github.com/apekshittewathia/Nearby

https://github.com/okoyenzube/nearby-places

https://github.com/helix1/nearbypizza

**Comment by LakshayNagpal** [comment]
@arp95 

first two are the major one.

https://github.com/slidenerd/CofShop

The screenshot shown in this repo readme is exactly what we want in our app.
You can take reference from it and modify it's code.

**Comment by arp95** [comment]
@LakshayNagpal
having a look.

**Comment by LakshayNagpal** [comment]
@arp95 

Any progress?
Did the above mentioned repos helped?

**Comment by arp95** [comment]
@LakshayNagpal 
please merge my latest pr.
Closing this as its solved now!
